<?php

use App\Enums\PersonNameType;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Alternate, native, historical and translated spellings.
 *
 * This is why "Thawng Dam", "Thawngdam" and "Thawng Dham" find the same
 * ancestor. `normalized` and `phonetic` are generated by MatchKeyGenerator and
 * feed both search and duplicate detection.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('person_names', function (Blueprint $table) {
            $table->id();
            $table->publicUlid();

            $table->foreignId('person_id')->constrained('people')->cascadeOnDelete();

            $table->string('name', 191);
            $table->string('normalized', 191);
            $table->string('phonetic', 64)->nullable();
            $table->enum('type', PersonNameType::values())->default(PersonNameType::Alternate->value);
            $table->string('script', 20)->nullable();
            $table->string('language', 10)->nullable();
            $table->boolean('is_primary')->default(false);

            $table->unsignedBigInteger('source_id')->nullable();   // FK added once `sources` exists

            $table->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete();
            $table->softDeletesWithToken();
            $table->timestamps();

            $table->unique(['person_id', 'normalized', 'type', 'deleted_token'], 'uq_person_names');
            $table->index(['person_id', 'type'], 'idx_pn_person');
            $table->index('normalized', 'idx_pn_normalized');
            $table->index('phonetic', 'idx_pn_phonetic');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('person_names');
    }
};
